sudo: required
services:
  - docker

before_install:
  - docker build -t scottiecrump/learn-docker-react -f Dockerfile.dev .

script:
  - docker run scottiecrump/learn-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'learn-docker-react'
  env: 'LearnDockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-345964528117'
  bucket_path: 'learn-docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
